### PR TITLE
Updates modules for Standard changes in Spezi 0.7.0

### PR DESCRIPTION
**Pull request by vishnuravi**
# Updates module for Standard changes in Spezi 0.7.0

## :recycle: Current situation & Problem
Spezi 0.7.0 changes how `Standard`s are defined and has made using a `Standard` in a module optional. The SpeziStorage module previously required defining a `Standard` even though it does not use one. 

## :bulb: Proposed solution
Updates SpeziStorage to remove the `Standard` requirement, which makes it simpler to use.

### Testing
Tests have been updated.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vishnuravi** [comment]
@PSchmiedmayer the swiftlint error here in [Tests/UITests/TestApp/TestApp.swift](https://github.com/StanfordSpezi/SpeziStorage/pull/8/files#diff-d5a42f7793be05ca51ed27f1ec3e1641da0e9678db76090fa49ad0c3400b7443) appears to be a false positive? I have not edited this file. (See related issue: https://github.com/realm/SwiftLint/issues/4843)

**Comment by bauer-andreas** [comment]
> @PSchmiedmayer the swiftlint error here in [Tests/UITests/TestApp/TestApp.swift](https://github.com/StanfordSpezi/SpeziStorage/pull/8/files#diff-d5a42f7793be05ca51ed27f1ec3e1641da0e9678db76090fa49ad0c3400b7443) appears to be a false positive? I have not edited this file. (See related issue: [realm/SwiftLint#4843](https://github.com/realm/SwiftLint/issues/4843))

If I may provide input on this.
You are seeing this issue due to an upgraded swiftlint version introduced with the new swiftlint GitHub action. 
We kinda came to the conclusion to just remove the attributes rule from the swiftlint config for now. At least that was what we were doing in most of the other projects. Maybe it’s worth creating a GitHub issue over at the ’.github’ project as we could discuss reintroducing the rule with a more customized configuration?

**Comment by vishnuravi** [comment]
> > @PSchmiedmayer the swiftlint error here in [Tests/UITests/TestApp/TestApp.swift](https://github.com/StanfordSpezi/SpeziStorage/pull/8/files#diff-d5a42f7793be05ca51ed27f1ec3e1641da0e9678db76090fa49ad0c3400b7443) appears to be a false positive? I have not edited this file. (See related issue: [realm/SwiftLint#4843](https://github.com/realm/SwiftLint/issues/4843))
> 
> If I may provide input on this. You are seeing this issue due to an upgraded swiftlint version introduced with the new swiftlint GitHub action. We kinda came to the conclusion to just remove the attributes rule from the swiftlint config for now. At least that was what we were doing in most of the other projects. Maybe it’s worth creating a GitHub issue over at the ’.github’ project as we could discuss reintroducing the rule with a more customized configuration?

Hi @Supereg thank you, that makes sense. I fixed this for the time being by setting `attributes_with_arguments_always_on_line_above` to false as described here: https://github.com/realm/SwiftLint/pull/4855.

**Review by PSchmiedmayer — APPROVED** [review]
@vishnuravi Thank you for the PR, that is very helpful! @niallkehoe that might also help you in taking a look at the Scheduler Module and the HPDS and PRISM apps 👍

Thank you @Supereg on the input! 
@vishnuravi I like the approach of using `attributes_with_arguments_always_on_line_above`, that looks like a clean solution here.

**Comment by vishnuravi** [comment]
The UI tests are passing locally, but are stuck on "Running..." on the UI test action. Will debug.

**Comment by PSchmiedmayer** [comment]
@vishnuravi I took a closer look at our build agents and fixed a few things. It should build now and should be ready to merge the PR 👍

**Comment by vishnuravi** [comment]
> @vishnuravi I took a closer look at our build agents and fixed a few things. It should build now and should be ready to merge the PR 👍

Thanks @PSchmiedmayer, glad the tests are passing now, will merge!

**Pull request merged**
